import type { RequirementPageConfig } from "./RequirementPage";
import SiteBreadcrumb from "../components/SiteBreadcrumb";

const sections = [
  ["O que é?", "A Lei Geral de Proteção de Dados - LGPD (Lei nº 13.709, de 2018) dispõe sobre o tratamento de dados pessoais das pessoas naturais (pessoas físicas), inclusive nos meios digitais. A lei se aplica ao tratamento, pela utilização, de dados pessoais realizado por pessoas naturais ou por pessoas jurídicas de direito público ou privado, e tem o objetivo de proteger os direitos fundamentais de liberdade e de privacidade e o livre desenvolvimento da personalidade da pessoa natural."],
  ["Quem é o titular dos dados pessoais?", "O titular dos dados pessoais é a pessoa natural (pessoa física) a quem pertencem os dados pessoais que são objeto de tratamento, ou seja, que são utilizados."],
  ["Quem é controlador?", "O Controlador é pessoa natural ou jurídica, de direito público ou privado, a quem competem as decisões referentes ao tratamento de dados pessoais - Lei Geral de Proteção de Dados (LGPD, Lei nº 13.709, de 2018). No caso em questão, o Controlador é a Prefeitura Municipal de Roseira."],
  ["Quem é a Autoridade Nacional de Proteção de Dados?", "A ANPD é a Autoridade Nacional de Proteção de Dados, órgão da Administração pública responsável por zelar; implementar e fiscalizar o cumprimento desta Lei em todo território nacional."],
];
const rights = ["I - confirmação da existência de tratamento;", "II - acesso aos dados;", "III – correção de dados incompletos, inexatos ou desatualizados;", "IV - anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou tratados em desconformidade com o disposto nesta lei;", "V - portabilidade dos dados a outros fornecedores de serviços ou produtos, mediante requisição expressa, de acordo com a regulamentação da autoridade nacional, observando os segredos comercial e industrial.", "VI - eliminação dos dados pessoais tratados com o consentimento do titular, exceto nas hipóteses previstas no art. 16 da LGPD.", "VII - informação das necessidades públicas e privadas com os quais o Controlador realizou uso compartilhado de dados.", "VIII - informação sobre a possibilidade de não fornecer consentimento e sobre as consequências da negativa.", "IX - revogação do consentimento, nos termos do §5º do art. 8º da LGPD."];

export default function LgpdPage({ onBackHome }: { page: RequirementPageConfig; onBackHome: () => void }) {
  return <div className="politica-cookies-view lgpd-page-view"><section className="site-internal-hero concursos-hero requirement-hero politica-cookies-hero"><div className="max-w-7xl mx-auto px-4"><SiteBreadcrumb items={[{ label: "Início", onClick: onBackHome }, { label: "A Prefeitura" }, { label: "LGPD" }]} /><div className="requirement-hero-grid"><div><h1 className="site-title">LGPD</h1></div></div></div></section><main className="politica-cookies-content"><div className="max-w-7xl mx-auto px-4"><article className="politica-cookies-card">{sections.map(([title, text]) => <section className="politica-cookies-section" key={title}><h2>{title}</h2><p>{text}</p></section>)}<section className="politica-cookies-section"><h2>Direitos do titular dos dados pessoais</h2><p>O titular dos dados pessoais tem direito a obter do controlador, em relação aos dados do titular por ele tratados, a qualquer momento e mediante requisição:</p><div className="lgpd-rights-list">{rights.map((right) => <p key={right}>{right}</p>)}</div></section></article></div></main></div>;
}
