import { Building2, FileText, Gavel, Home, Landmark, Newspaper, Scale, Settings, ShieldCheck, Trophy, Users } from "lucide-react";
import type { RequirementPageConfig } from "./RequirementPage";
import SiteBreadcrumb from "../components/SiteBreadcrumb";

type SiteLink = { label: string; href: string };
type SiteGroup = { title: string; icon: typeof Home; links: SiteLink[] };
const prefeitura = (slug: string) => `/prefeitura/${encodeURIComponent(slug)}`;
const groups: SiteGroup[] = [
  { title: "A Prefeitura", icon: Landmark, links: [{ label: "História de Roseira", href: "/historia" }, { label: "Prefeito e Vice-prefeito", href: prefeitura("prefeito-vice") }, { label: "Gabinete", href: prefeitura("gabinete") }, { label: "Estrutura Administrativa", href: prefeitura("estrutura-administrativa") }, { label: "Telefones e Endereços", href: prefeitura("telefones-enderecos") }, { label: "Horário de Atendimento", href: prefeitura("horario-atendimento") }, { label: "Símbolos Municipais", href: prefeitura("símbolos-municipais") }, { label: "Conselhos Municipais", href: prefeitura("conselhos-municipais") }, { label: "Mapa do Site", href: prefeitura("mapa-site") }, { label: "Galeria de Fotos", href: prefeitura("galeria-fotos") }, { label: "Termos de Uso", href: prefeitura("termos-uso") }, { label: "Política de Cookies", href: prefeitura("politica-cookies") }, { label: "LGPD", href: prefeitura("lgpd") }] },
  { title: "Secretarias", icon: Building2, links: [{ label: "Esporte", href: "/secretarias/esporte" }, { label: "Saúde", href: "/secretarias/saude" }, { label: "Conselho Municipal de Educação", href: prefeitura("conselho-educacao") }, { label: "Educação", href: "/secretarias/educacao" }, { label: "FUNDEB", href: "/secretarias/fundeb" }, { label: "Conselho de Alimentação Escolar", href: prefeitura("conselho-alimentacao-escolar") }, { label: "Vagas em Creche", href: prefeitura("vagas-creche") }, { label: "Turismo e Cultura", href: prefeitura("turismo-cultura") }, { label: "Meio Ambiente", href: prefeitura("meio-ambiente") }, { label: "Cadastro de Inscrição Municipal", href: prefeitura("cadastro-inscrição-municipal") }] },
  { title: "Serviços", icon: Settings, links: [{ label: "Carta de Serviços", href: "/servicos/carta-servicos" }, { label: "Serviços ao Cidadão", href: "/servicos/servicos-cidadao" }, { label: "Serviços à Empresa", href: "/servicos/servicos-empresa" }, { label: "Serviços ao Servidor", href: "/servicos/servicos-servidor" }, { label: "Protocolos", href: prefeitura("protocolos") }, { label: "Emissão de Guias", href: prefeitura("emissão-guias") }, { label: "IPTU", href: prefeitura("iptu") }, { label: "Dívida Ativa", href: prefeitura("dívida-ativa") }, { label: "ITBI", href: prefeitura("itbi") }, { label: "Nota Fiscal Eletrônica", href: prefeitura("nota-fiscal-eletrônica") }, { label: "Perguntas Frequentes", href: "/perguntas-frequentes" }] },
  { title: "Notícias", icon: Newspaper, links: [{ label: "Últimas Notícias", href: "/noticias" }, { label: "Comunicados", href: "/noticias/comunicados" }, { label: "Agenda de Eventos", href: "/noticias/eventos" }, { label: "Campanhas", href: "/noticias/campanhas" }, { label: "Boletins Oficiais", href: "/noticias/boletins-oficiais" }] },
  { title: "Licitações", icon: Gavel, links: [{ label: "Licitações em Aberto", href: "/licitacoes/em-aberto" }, { label: "Licitações Encerradas", href: "/licitacoes/encerradas" }, { label: "Concorrência Pública", href: "/licitacoes/concorrencia-publica" }, { label: "Chamada Pública", href: "/licitacoes/chamada-publica" }, { label: "Pregão Presencial", href: "/licitacoes/pregao-presencial" }, { label: "Tomada de Preços", href: "/licitacoes/tomada-de-precos" }, { label: "Leilão", href: "/licitacoes/leilao" }, { label: "Contratos", href: "/licitacoes/contratos" }, { label: "PNCP", href: "/licitacoes/pncp" }] },
  { title: "Concursos", icon: Trophy, links: [{ label: "Concursos", href: "/concursos" }] },
  { title: "Transparência", icon: ShieldCheck, links: [{ label: "Portal da Transparência", href: "/transparencia/portal-transparencia" }, { label: "Receitas", href: "/transparencia/receitas" }, { label: "Despesas", href: "/transparencia/despesas" }, { label: "Folha de Pagamento", href: "/transparencia/folha-pagamento" }, { label: "Obras Públicas", href: "/transparencia/obras-públicas" }, { label: "Dados Abertos", href: "/transparencia/dados-abertos" }] },
  { title: "Legislação", icon: Scale, links: [{ label: "Leis Municipais", href: "/legislacao/leis-municipais" }, { label: "Lei Orgânica Municipal", href: prefeitura("lei-organica-municipal") }, { label: "Decretos", href: "/legislacao/decretos" }, { label: "Portarias", href: "/legislacao/portarias" }, { label: "Código Tributário", href: prefeitura("codigo-tributario") }] },
  { title: "Contato", icon: Users, links: [{ label: "Endereço e Telefones", href: "/contato/endereco-telefones" }, { label: "Horários de Atendimento", href: "/contato/horarios-atendimento" }, { label: "Mapa de Localização", href: "/contato/mapa-localizacao" }, { label: "Ouvidoria", href: "/contato/ouvidoria" }, { label: "e-SIC", href: "/contato/e-sic" }] },
];

export default function MapaSitePage({ onBackHome }: { page: RequirementPageConfig; onBackHome: () => void }) {
  return <div className="mapa-site-view"><section className="site-internal-hero concursos-hero requirement-hero"><div className="max-w-7xl mx-auto px-4"><SiteBreadcrumb items={[{ label: "Início", onClick: onBackHome }, { label: "A Prefeitura" }, { label: "Mapa do Site" }]} /><div className="requirement-hero-grid"><div><h1 className="site-title">Mapa do Site</h1><p className="site-subtitle">Índice navegável das áreas institucionais, serviços, transparência, legislação e contato.</p></div></div></div></section><section className="mapa-site-content"><div className="max-w-7xl mx-auto px-4"><article className="mapa-site-card"><div className="mapa-site-grid">{groups.map(({ title, icon: Icon, links }) => <section className="mapa-site-group" key={title}><h2><Icon aria-hidden="true" />{title}</h2><ul>{links.map((link) => <li key={link.label}><a href={link.href}>› {link.label}</a></li>)}</ul></section>)}</div></article></div></section></div>;
}
