import { useState } from "react";
import { BookOpen, ClipboardList, FileText, ShieldCheck } from "lucide-react";
import SiteBreadcrumb from "../components/SiteBreadcrumb";
import type { RequirementPageConfig } from "./RequirementPage";

const officialUrl = "https://www.roseira.sp.gov.br/ouvidoria";
const reportsUrl = "https://www.roseira.sp.gov.br/ouvidoria/relatorio/relatorio-download/1/";
const bannerTabs = [{ id: "acesso", label: "Acesso e cadastro", icon: ClipboardList, tone: "yellow" }, { id: "prazos", label: "Prazos e respostas", icon: FileText, tone: "green" }, { id: "orientacoes", label: "Orientações", icon: ShieldCheck, tone: "red" }, { id: "relatorios", label: "Relatórios", icon: BookOpen, tone: "cp" }] as const;

export default function OuvidoriaPage({ onBackHome }: { page: RequirementPageConfig; onBackHome: () => void }) {
  const [activeBannerTab, setActiveBannerTab] = useState("acesso");
  return <div className="requirement-page ouvidoria-page"><section className="site-internal-hero concursos-hero requirement-hero"><div className="max-w-7xl mx-auto px-4"><SiteBreadcrumb items={[{ label: "Início", onClick: onBackHome }, { label: "Contato" }, { label: "Ouvidoria" }]} /><div className="requirement-hero-grid"><div><h1 className="site-title">Ouvidoria Pública Municipal</h1><div className="concursos-summary-grid ouvidoria-hero-actions" aria-label="Acesso rápido às seções da Ouvidoria">{bannerTabs.map(({ id, label, icon: Icon, tone }) => <button key={id} type="button" title={label} aria-pressed={activeBannerTab === id} className={`concursos-summary-card ${activeBannerTab === id ? "concursos-summary-card-active" : ""}`} onClick={() => setActiveBannerTab(id)}><span className={`concursos-summary-icon concursos-summary-icon-${tone}`}><Icon aria-hidden="true" /></span><span><strong className="site-card-title">{label}</strong><small className="site-text">Acessar seção</small></span></button>)}</div></div></div></div></section><section className="requirement-content" aria-labelledby="ouvidoria-title"><div className="max-w-7xl mx-auto px-4"><div id="ouvidoria-content" role="tabpanel" aria-live="polite" tabIndex={0} className="ouvidoria-content-panel">
{activeBannerTab === "acesso" && <article className="requirement-panel ouvidoria-single-card"><h2 id="ouvidoria-title">O que é a ouvidoria?</h2><p className="requirement-panel-text">A Ouvidoria Pública é o canal oficial para que qualquer cidadão registre sugestões, elogios, solicitações, reclamações e denúncias junto ao poder público.</p><a className="site-green-pill-button requirement-source-link" href={officialUrl} target="_blank" rel="noreferrer" title="Abrir chamado">Abrir chamado<span className="sr-only"> (abre em nova aba)</span></a></article>}
{activeBannerTab === "prazos" && <article className="requirement-panel"><h2>Prazo para resposta</h2><p className="requirement-panel-text">Os prazos de resposta da Ouvidoria variam conforme a categoria da manifestação. O prazo começa a contar a partir da data de abertura do chamado e pode haver prorrogação, quando prevista para a categoria.</p><p className="requirement-panel-text">Enquanto o chamado estiver com status <strong>Novo</strong>, <strong>Em progresso</strong> ou <strong>Aguardando resposta</strong>, a contagem continua normalmente. Quando o chamado for <strong>Finalizado</strong> ou <strong>Indeferido</strong>, a contagem é encerrada.</p><div className="requirement-table-wrap"><table className="requirement-table"><caption className="sr-only">Prazos de resposta por categoria</caption><thead><tr><th scope="col">Categoria</th><th scope="col">Prazo inicial</th><th scope="col">Prorrogação</th></tr></thead><tbody>{[["Denúncia", "30 dias", "30 dias"], ["Elogio", "30 dias", "30 dias"], ["Informação (LAI)", "20 dias", "10 dias"], ["Reclamação", "30 dias", "30 dias"], ["Solicitação", "30 dias", "30 dias"], ["Sugestão", "30 dias", "30 dias"]].map(row => <tr key={row[0]}>{row.map((cell, index) => index === 0 ? <th scope="row" key={cell}>{cell}</th> : <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div><p className="requirement-panel-text">Quando o chamado estiver com status <strong>Finalizado</strong> ou <strong>Indeferido</strong>, o cidadão poderá solicitar recurso caso discorde da resposta recebida ou deseje apresentar novas informações. O prazo para solicitar recurso é de <strong>10 dias</strong>. Após o envio da solicitação de recurso, o responsável terá o prazo de <strong>5 dias</strong> para analisar e responder.</p><div className="requirement-table-wrap"><table className="requirement-table"><caption className="sr-only">Prazos de recurso</caption><thead><tr><th scope="col">Prazo para o cidadão recorrer</th><th scope="col">Prazo para manifestação do órgão</th></tr></thead><tbody><tr><td>10 dias</td><td>5 dias</td></tr></tbody></table></div></article>}
{activeBannerTab === "orientacoes" && <div className="ouvidoria-guidance-grid"><article className="requirement-panel"><h2>Prevenção e combate ao assédio e à discriminação</h2><p className="requirement-panel-text">Saiba o que é assédio e discriminação, como identificar situações de abuso, como registrar uma denúncia com sigilo e quais são os seus direitos garantidos por lei.</p><a className="site-green-pill-button requirement-source-link" href={officialUrl} target="_blank" rel="noreferrer" title="Saiba mais sobre assédio e discriminação">Clique aqui para saber mais<span className="sr-only"> (abre em nova aba)</span></a></article><article className="requirement-panel"><h2>Prevenção e combate à violência contra mulheres</h2><p className="requirement-panel-text">Informações sobre os tipos de violência contra a mulher, sinais de alerta, canais de apoio disponíveis 24 horas e instruções de como denunciar com total segurança e sigilo.</p><a className="site-green-pill-button requirement-source-link" href={officialUrl} target="_blank" rel="noreferrer" title="Saiba mais sobre violência contra mulheres">Clique aqui para saber mais<span className="sr-only"> (abre em nova aba)</span></a></article></div>}
{activeBannerTab === "relatorios" && <article className="requirement-panel"><h2>Relatórios da Ouvidoria</h2><div className="requirement-table-wrap"><table className="requirement-table"><caption className="sr-only">Relatórios de atividades da Ouvidoria</caption><thead><tr><th scope="col">Relatório</th><th scope="col">Acesso</th></tr></thead><tbody><tr><td>Relatório de atividades da Ouvidoria — segundo trimestre 2026</td><td><a href={reportsUrl} target="_blank" rel="noreferrer" title="Baixar relatório do segundo trimestre de 2026">Download</a></td></tr><tr><td>Relatório de atividades da Ouvidoria — primeiro trimestre 2026</td><td><a href={reportsUrl} target="_blank" rel="noreferrer" title="Baixar relatório do primeiro trimestre de 2026">Download</a></td></tr></tbody></table></div></article>}
</div></div></section></div>;
}