import type { RequirementPageConfig } from "./RequirementPage";
import SiteBreadcrumb from "../components/SiteBreadcrumb";

const sections = [
  { title: "1.1 - O que são cookies?", paragraphs: ["Como é prática comum em quase todos os sites profissionais, este site usa cookies, que são pequenos arquivos baixados no seu computador, para melhorar sua experiência. Esta página descreve quais informações eles coletam, como as usamos e por que às vezes precisamos armazenar esses cookies. Também compartilharemos como você pode impedir que esses cookies sejam armazenados, no entanto, isso pode fazer o downgrade ou 'quebrar' certos elementos da funcionalidade do site."] },
  { title: "1.2 - Como usamos os cookies?", paragraphs: ["Utilizamos cookies por vários motivos, detalhados abaixo. Infelizmente, na maioria dos casos, não existem opções padrão do setor para desativar os cookies sem desativar completamente a funcionalidade e os recursos que eles adicionam a este site. É recomendável que você deixe todos os cookies se não tiver certeza se precisa ou não deles, caso sejam usados para fornecer um serviço que você usa."] },
  { title: "1.3 - Desativar cookies", paragraphs: ["Utilizamos cookies por vários motivos, detalhados abaixo. Infelizmente, na maioria dos casos, não existem opções padrão do setor para desativar os cookies sem desativar completamente a funcionalidade e os recursos que eles adicionam a este site. É recomendável que você deixe todos os cookies se não tiver certeza se precisa ou não deles, caso sejam usados para fornecer um serviço que você usa."] },
  { title: "1.4 - Cookies que definimos:", paragraphs: [], children: [{ title: "1.4.1 - Cookies relacionados à conta", text: "Se você criar uma conta conosco, usaremos cookies para o gerenciamento do processo de inscrição e administração geral. Esses cookies geralmente serão excluídos quando você sair do sistema, porém, em alguns casos, eles poderão permanecer posteriormente para lembrar as preferências do seu site ao sair." }, { title: "1.4.2 - Cookies relacionados ao login", text: "Utilizamos cookies quando você está logado, para que possamos lembrar dessa ação. Isso evita que você precise fazer login sempre que visitar uma nova página. Esses cookies são normalmente removidos ou limpos quando você efetua logout para garantir que você possa acessar apenas a recursos e áreas restritas ao efetuar login." }] },
  { title: "1.5 - Pedidos processando cookies relacionados:", paragraphs: [], children: [{ title: "1.5.1", text: "Este site oferece facilidades de comércio eletrônico ou pagamento e alguns cookies são essenciais para garantir que seu pedido seja lembrado entre as páginas, para que possamos processá-lo adequadamente." }] },
  { title: "1.6 - Cookies relacionados a formulários:", paragraphs: [], children: [{ title: "1.6.1", text: "Quando você envia dados por meio de um formulário como os encontrados nas páginas de contato ou em outros formulários, os cookies podem ser configurados para lembrar os detalhes do usuário para correspondência futura." }] },
  { title: "1.7 - Cookies de preferências do site:", paragraphs: [], children: [{ title: "1.7.1", text: "Para proporcionar uma ótima experiência neste site, fornecemos a funcionalidade para definir suas preferências de como esse site é executado quando você o usa. Para lembrar suas preferências, precisamos definir cookies para que essas informações possam ser chamadas sempre que você interagir com uma página afetada por suas preferências." }] },
  { title: "1.8 - Cookies de Terceiros:", paragraphs: [], children: [{ title: "1.8.1", text: "Em alguns casos especiais, também usamos cookies fornecidos por terceiros confiáveis. A seção a seguir detalha quais cookies de terceiros você pode encontrar através deste site." }, { title: "1.8.2", text: "Este site usa o Matomo, que é uma das soluções de análise mais difundidas e confiáveis da Web, para nos ajudar a entender como você usa o site e como podemos melhorar sua experiência. Esses cookies podem rastrear itens como quanto tempo você gasta no site e as páginas visitadas, para que possamos contabilizar o número de visitantes nas páginas do site. Para mais informações sobre cookies do Matomo, consulte a página oficial do Matomo." }] },
];

export default function PoliticaCookiesPage({ onBackHome }: { page: RequirementPageConfig; onBackHome: () => void }) {
  return <div className="politica-cookies-view"><section className="site-internal-hero concursos-hero requirement-hero politica-cookies-hero"><div className="max-w-7xl mx-auto px-4"><SiteBreadcrumb items={[{ label: "Início", onClick: onBackHome }, { label: "A Prefeitura" }, { label: "Política de Cookies" }]} /><div className="requirement-hero-grid"><div><h1 className="site-title">Política de Cookies</h1></div></div></div></section><main className="politica-cookies-content"><div className="max-w-7xl mx-auto px-4"><article className="politica-cookies-card">{sections.map((section) => <section className="politica-cookies-section" key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.children?.map((child) => <div className="politica-cookies-child" key={child.title}><h3>{child.title}</h3><p>{child.text}</p></div>)}</section>)}</article></div></main></div>;
}
