import { CalendarDays, Clock, Mail, MapPin, Phone, UserRound } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import type { RequirementPageConfig } from "./RequirementPage";
import SiteBreadcrumb from "../components/SiteBreadcrumb";

type PersonKey = "prefeito" | "vice";
type Tab = PersonKey | "agenda";
type Appointment = { id: string; person: PersonKey; date: string; time: string; title: string; location: string; description: string };
const STORAGE_KEY = "roseira-agenda-prefeito-vice";
const people: Record<PersonKey, { label: string; role: string }> = { prefeito: { label: "Prefeito", role: "Chefe do Poder Executivo" }, vice: { label: "Vice-prefeito", role: "Vice-chefe do Poder Executivo" } };

function ContactCard({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <article className="secretaria-detail-contact-card prefeito-contact-card"><span className="sx-185 secretaria-detail-contact-icon">{icon}</span><div><strong className="site-card-title">{label}</strong><p className="site-text">{value}</p></div></article>; }
function PersonPanel({ person }: { person: PersonKey }) { const data = people[person]; return <div className="prefeito-person-layout"><article className="prefeito-profile-card"><div className="prefeito-photo-placeholder"><UserRound aria-hidden="true" /><span>Foto oficial</span></div><div><span className="site-caps-title">{data.label}</span><h2 className="site-panel-title">Não declarado</h2><p className="site-text">{data.role}</p><p className="prefeito-pending-note">Nome, foto e biografia aguardam publicação oficial.</p></div></article><div className="prefeito-info-grid"><article className="secretaria-detail-panel"><h2 className="site-panel-title">Informações institucionais</h2><dl className="prefeito-data-list"><div><dt>Mandato</dt><dd>Não declarado</dd></div><div><dt>Biografia</dt><dd>Não declarada</dd></div><div><dt>Contato institucional</dt><dd>Não declarado</dd></div></dl></article><article className="prefeito-calendar-card sx-132"><div className="sx-135"><button type="button" className="sx-136" title="Mês anterior" aria-label="Mês anterior">‹</button><span className="sx-137">Ago 2026</span><button type="button" className="sx-138" title="Próximo mês" aria-label="Próximo mês">›</button></div><div className="sx-139"><div className="sx-140">{["D", "S", "T", "Q", "Q", "S", "S"].map((day, index) => <div key={index} className="sx-141">{day}</div>)}</div><div className="sx-142">{Array.from({ length: 6 }).map((_, index) => <div key={`empty-${index}`} />)}{Array.from({ length: 31 }).map((_, index) => { const day = index + 1; const hasEvent = [12, 15, 18, 22, 29].includes(day); const today = day === 10; return <div key={day} className={`sx-143 ${today ? "calendar-day-today" : hasEvent ? "calendar-day-event" : "calendar-day-normal"}`}>{day}{hasEvent && !today && <div className="sx-144" />}</div>; })}</div></div></article></div></div>; }

export default function PrefeitoVicePage({ onBackHome }: { page: RequirementPageConfig; onBackHome: () => void }) {
  const [tab, setTab] = useState<Tab>("prefeito");
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [agendaPerson, setAgendaPerson] = useState<PersonKey>("prefeito");
  useEffect(() => { try { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved) setAppointments(JSON.parse(saved) as Appointment[]); } catch { /* armazenamento indisponível */ } }, []);
  const visibleAppointments = appointments.filter((item) => item.person === agendaPerson);
  return <div className="secretaria-detail-view prefeito-vice-page">
    <section className="site-internal-hero secretaria-detail-hero prefeito-vice-hero"><div className="max-w-7xl mx-auto px-4"><SiteBreadcrumb items={[{ label: "Início", onClick: onBackHome }, { label: "A Prefeitura" }, { label: "Prefeito e Vice-prefeito" }]} /><div className="secretaria-detail-hero-row"><div><h1 className="site-title">Prefeito e Vice-prefeito</h1><p className="site-subtitle">Conheça os responsáveis pelo Poder Executivo e acompanhe seus compromissos públicos.</p></div></div></div></section>
    <section className="secretaria-detail-contacts prefeito-contacts"><div className="max-w-7xl mx-auto px-4"><div className="secretaria-detail-contact-grid"><ContactCard icon={<MapPin aria-hidden="true" />} label="Endereço" value="Não declarado" /><ContactCard icon={<Clock aria-hidden="true" />} label="Horário de atendimento" value="Não declarado" /><ContactCard icon={<Phone aria-hidden="true" />} label="Telefone" value="Não declarado" /><ContactCard icon={<Mail aria-hidden="true" />} label="E-mail" value="Não declarado" /></div></div></section>
    <nav className="secretaria-detail-tabs prefeito-vice-tabs" aria-label="Seções do Prefeito e Vice-prefeito"><div className="max-w-7xl mx-auto px-4">{([{ id: "prefeito", label: "Prefeito" }, { id: "vice", label: "Vice-prefeito" }] as Array<{ id: Tab; label: string }>).map((item) => <button key={item.id} type="button" role="tab" aria-selected={tab === item.id} className={tab === item.id ? "prefeito-tab-active site-card-title" : "site-card-title"} onClick={() => setTab(item.id)}>{item.label}</button>)}</div></nav>
    <section className="secretaria-detail-main prefeito-vice-main"><div className="max-w-7xl mx-auto px-4">{tab !== "agenda" ? <PersonPanel person={tab} /> : <div className="agenda-public-layout"><article className="secretaria-detail-panel agenda-filter-card"><span className="site-caps-title">Compromissos públicos</span><h2 className="site-panel-title">Agenda</h2><p className="site-text">Consulte os compromissos publicados pela Prefeitura.</p><div className="agenda-person-filter" role="tablist" aria-label="Responsável pela agenda"><button type="button" role="tab" aria-selected={agendaPerson === "prefeito"} className={agendaPerson === "prefeito" ? "agenda-person-active" : ""} onClick={() => setAgendaPerson("prefeito")}>Prefeito</button><button type="button" role="tab" aria-selected={agendaPerson === "vice"} className={agendaPerson === "vice" ? "agenda-person-active" : ""} onClick={() => setAgendaPerson("vice")}>Vice-prefeito</button></div></article><article className="secretaria-detail-panel agenda-list-card"><div className="agenda-list-heading"><div><span className="site-caps-title">Agenda publicada</span><h2 className="site-panel-title">Agenda do {people[agendaPerson].label}</h2></div><CalendarDays aria-hidden="true" /></div>{visibleAppointments.length === 0 ? <p className="site-text agenda-empty">Nenhum compromisso publicado.</p> : <div className="agenda-items">{visibleAppointments.map((item) => <article className="agenda-item" key={item.id}><div className="agenda-item-date"><strong>{new Date(`${item.date}T12:00:00`).toLocaleDateString("pt-BR", { day: "2-digit", month: "short" }).replace(".", "")}</strong><span>{item.time}</span></div><div><h3>{item.title}</h3>{item.location && <p className="site-text">{item.location}</p>}{item.description && <p className="site-text">{item.description}</p>}</div></article>)}</div>}</article></div>}</div></section>
  </div>;
}

