import SiteBreadcrumb from "../components/SiteBreadcrumb";
import type { RequirementPageConfig } from "./RequirementPage";

type Section = { title: string; paragraphs: string[]; items?: string[] };

const sections: Section[] = [
  { title: "1. Finalidade do portal", paragraphs: ["O Portal da Prefeitura Municipal de Roseira tem a finalidade de oferecer informações institucionais, serviços públicos, notícias, legislação, transparência e canais de atendimento à população.", "O conteúdo é disponibilizado para facilitar o acesso a informações de interesse público e orientar o cidadão sobre os serviços municipais."] },
  { title: "2. Aceitação e condições de uso", paragraphs: ["Ao acessar e utilizar este portal, o usuário declara que leu e concorda com estes Termos de Uso e com a legislação aplicável.", "O uso do portal deve ocorrer de forma responsável, lícita e compatível com sua finalidade pública. O usuário não deve utilizar o site para praticar atos que prejudiquem seu funcionamento, a segurança dos sistemas ou os direitos de terceiros."] },
  { title: "3. Responsabilidades do usuário", paragraphs: ["É responsabilidade do usuário utilizar as informações e os serviços do portal de acordo com a legislação vigente e com a finalidade para a qual foram disponibilizados."], items: ["Não inserir, transmitir ou disseminar conteúdo ilícito, falso, ofensivo ou que viole direitos de terceiros.", "Não tentar obter acesso não autorizado a áreas restritas, sistemas, contas ou dados.", "Conferir as orientações e os documentos exigidos antes de solicitar um serviço ou protocolar uma demanda.", "Manter seus dados de contato corretos quando o serviço solicitar cadastro ou comunicação."] },
  { title: "4. Informações e serviços públicos", paragraphs: ["A Prefeitura busca manter as informações atualizadas, claras e acessíveis. Prazos, documentos, endereços, horários e condições de atendimento podem ser alterados por atos administrativos ou por mudanças na prestação do serviço.", "Quando houver canal oficial específico, o portal poderá direcionar o usuário para sistemas próprios ou para páginas de órgãos e entidades responsáveis pelo atendimento."] },
  { title: "5. Direitos do usuário", paragraphs: ["O usuário tem direito de acessar as informações públicas disponíveis, utilizar os canais de atendimento, solicitar esclarecimentos e comunicar erros, indisponibilidades ou informações desatualizadas."], items: ["Receber informações claras sobre os serviços e seus requisitos.", "Consultar os canais oficiais de atendimento e acompanhamento de solicitações.", "Solicitar correção de informação pessoal quando aplicável.", "Obter atendimento sem discriminação, observadas as regras e os requisitos legais de cada serviço."] },
  { title: "6. Conteúdo, links e propriedade intelectual", paragraphs: ["Textos, marcas, logotipos, imagens e demais elementos do portal pertencem à Prefeitura ou aos respectivos titulares, salvo indicação em contrário. A reprodução deve respeitar a legislação e informar a fonte.", "Links para sites externos são disponibilizados para facilitar o acesso a serviços ou informações. A Prefeitura não controla o conteúdo, a disponibilidade ou as políticas desses sites externos."] },
  { title: "7. Privacidade e proteção de dados", paragraphs: ["O tratamento de dados pessoais realizado por este portal observa a legislação aplicável e as informações apresentadas na Política de Cookies e na página de LGPD. O usuário deve consultar esses documentos para conhecer os canais, direitos e condições relacionados ao tratamento de dados pessoais."] },
  { title: "8. Disponibilidade e alterações", paragraphs: ["O portal pode passar por manutenção, atualizações ou interrupções temporárias para melhoria dos serviços e segurança da infraestrutura. A Prefeitura poderá alterar estes Termos de Uso quando necessário, mantendo nesta página a versão vigente."] },
  { title: "9. Atendimento e contato", paragraphs: ["Dúvidas, sugestões, comunicações de erro ou solicitações relacionadas ao portal podem ser encaminhadas pelos canais oficiais de atendimento da Prefeitura Municipal de Roseira, disponíveis na página de Contato."] },
];

export default function TermosUsoPage({ page, onBackHome }: { page: RequirementPageConfig; onBackHome: () => void }) {
  return <div className="politica-cookies-view termos-uso-view"><section className="site-internal-hero concursos-hero requirement-hero politica-cookies-hero"><div className="max-w-7xl mx-auto px-4"><SiteBreadcrumb items={[{ label: "Início", onClick: onBackHome }, { label: "A Prefeitura" }, { label: "Termos de Uso" }]} /><div className="requirement-hero-grid"><div><h1 className="site-title">Termos de Uso</h1></div></div></div></section><main className="politica-cookies-content"><div className="max-w-7xl mx-auto px-4"><article className="politica-cookies-card termos-uso-card"><p className="termos-uso-updated">Data de atualização: 23 de setembro de 2026</p>{sections.map((section) => <section className="politica-cookies-section" key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.items && <ul className="termos-uso-list">{section.items.map((item) => <li key={item}>{item}</li>)}</ul>}</section>)}</article></div></main></div>;
}